# File: .github/workflows/build-and-deploy-jar-to-azure.yml
name: Build and deploy JAR app to Azure Web App - MyAddressBook

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: maven

      - name: Build with Maven
        working-directory: lab
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: lab/target/*.jar

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: java-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_65B0DC695EB24C1091270C36ACE214B4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B87588DE77974464A967C16C77DE4F3A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_44AE12275BEC490695B0C250E6303EC3 }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyAddressBook'
          slot-name: 'Production'
          package: '*.jar'
