# .github/workflows/build-and-deploy-jar-to-azure.yml
name: Build and deploy JAR app to Azure Web App - MyAddressBook

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: maven

      - name: Build with Maven
        working-directory: lab
        run: mvn clean install

      - name: List produced files (debug)
        run: dir lab/target        

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: lab/target/*.jar     

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: java-app

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9B75F253ADA4D529C8C8FB74D50A8C5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A02082ECB5D34A37BCF3443E1DA4CD3C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2E9BDBF26A6F4B358B5B0D7F46ABD892 }}

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyAddressBook'
          slot-name: 'Production'
          package: '*.jar'
