name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:        <-- REMOVE THIS BLOCK
    #   run:
    #     working-directory: lab4

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven

    - name: Build & test
      working-directory: lab
      run: mvn --batch-mode --update-snapshots verify   # one step is enough
